<a href="https://www.kaggle.com/code/swish9/bank-marketing-data-accuracy-89?scriptVersionId=120526862" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Importing Libraries

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset = pd.read_csv('/kaggle/input/bank-marketing-data/bank-full.csv',sep=';')

In [3]:
y = dataset["y"]
dataset.drop("y", axis=1,inplace = True)

In [4]:
dataset.head(10)

age           job   marital  education default  balance housing loan  \
0   58    management   married   tertiary      no     2143     yes   no   
1   44    technician    single  secondary      no       29     yes   no   
2   33  entrepreneur   married  secondary      no        2     yes  yes   
3   47   blue-collar   married    unknown      no     1506     yes   no   
4   33       unknown    single    unknown      no        1      no   no   
5   35    management   married   tertiary      no      231     yes   no   
6   28    management    single   tertiary      no      447     yes  yes   
7   42  entrepreneur  divorced   tertiary     yes        2     yes   no   
8   58       retired   married    primary      no      121     yes   no   
9   43    technician    single  secondary      no      593     yes   no   

   contact  day month  duration  campaign  pdays  previous poutcome  
0  unknown    5   may       261         1     -1         0  unknown  
1  unknown    5   may       151         1     -1         0  unknown  
2  unknown    5   may        76         1     -1         0  unknown  
3  unknown    5   may        92         1     -1         0  unknown  
4  unknown    5   may       198         1     -1         0  unknown  
5  unknown    5   may       139         1     -1         0  unknown  
6  unknown    5   may       217         1     -1         0  unknown  
7  unknown    5   may       380         1     -1         0  unknown  
8  unknown    5   may        50         1     -1         0  unknown  
9  unknown    5   may        55         1     -1         0  unknown

In [5]:
dataset.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome'],
      dtype='object')

In [6]:
dataset.nunique()

age            77
job            12
marital         3
education       4
default         2
balance      7168
housing         2
loan            2
contact         3
day            31
month          12
duration     1573
campaign       48
pdays         559
previous       41
poutcome        4
dtype: int64

In [7]:
dataset.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
dtype: int64

SIGHS!!

In [8]:
dataset.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
dtype: object

In [9]:
dataset = dataset.drop(["default","contact","day","month","campaign","previous","poutcome"], axis=1)

In [10]:
dataset.columns

Index(['age', 'job', 'marital', 'education', 'balance', 'housing', 'loan',
       'duration', 'pdays'],
      dtype='object')

In [11]:
dataset.pdays.nunique()

559

In [12]:
dataset.pdays.value_counts()

-1      36954
 182      167
 92       147
 91       126
 183      126
        ...  
 449        1
 452        1
 648        1
 595        1
 530        1
Name: pdays, Length: 559, dtype: int64

In [13]:
dataset = dataset.drop(["pdays"], axis=1)

In [14]:
dataset.head(3)

age           job  marital  education  balance housing loan  duration
0   58    management  married   tertiary     2143     yes   no       261
1   44    technician   single  secondary       29     yes   no       151
2   33  entrepreneur  married  secondary        2     yes  yes        76

# Encoding Categorical columns 

In [15]:
dataset.loan.nunique()

2

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset.loan = le.fit_transform(dataset.loan)

In [17]:
dataset.housing.nunique()

2

In [18]:
dataset.housing = le.fit_transform(dataset.housing)

In [19]:
dataset.head(3)

age           job  marital  education  balance  housing  loan  duration
0   58    management  married   tertiary     2143        1     0       261
1   44    technician   single  secondary       29        1     0       151
2   33  entrepreneur  married  secondary        2        1     1        76

In [20]:
from sklearn.preprocessing import OneHotEncoder
cat_cols = [col for col in dataset.columns if dataset[col].dtype == 'object']
encoder = OneHotEncoder()
one_hot = encoder.fit_transform(dataset[cat_cols])
one_hot_df = pd.DataFrame(one_hot.toarray(), columns=encoder.get_feature_names_out(cat_cols))
dataset = pd.concat([dataset, one_hot_df], axis=1)

dataset.drop(cat_cols, axis=1, inplace=True)


In [21]:
# X.drop("y",inplace = True)
X = dataset
X

age  balance  housing  loan  duration  job_admin.  job_blue-collar  \
0       58     2143        1     0       261         0.0              0.0   
1       44       29        1     0       151         0.0              0.0   
2       33        2        1     1        76         0.0              0.0   
3       47     1506        1     0        92         0.0              1.0   
4       33        1        0     0       198         0.0              0.0   
...    ...      ...      ...   ...       ...         ...              ...   
45206   51      825        0     0       977         0.0              0.0   
45207   71     1729        0     0       456         0.0              0.0   
45208   72     5715        0     0      1127         0.0              0.0   
45209   57      668        0     0       508         0.0              1.0   
45210   37     2971        0     0       361         0.0              0.0   

       job_entrepreneur  job_housemaid  job_management  ...  job_technician  \
0                   0.0            0.0             1.0  ...             0.0   
1                   0.0            0.0             0.0  ...             1.0   
2                   1.0            0.0             0.0  ...             0.0   
3                   0.0            0.0             0.0  ...             0.0   
4                   0.0            0.0             0.0  ...             0.0   
...                 ...            ...             ...  ...             ...   
45206               0.0            0.0             0.0  ...             1.0   
45207               0.0            0.0             0.0  ...             0.0   
45208               0.0            0.0             0.0  ...             0.0   
45209               0.0            0.0             0.0  ...             0.0   
45210               1.0            0.0             0.0  ...             0.0   

       job_unemployed  job_unknown  marital_divorced  marital_married  \
0                 0.0          0.0               0.0              1.0   
1                 0.0          0.0               0.0              0.0   
2                 0.0          0.0               0.0              1.0   
3                 0.0          0.0               0.0              1.0   
4                 0.0          1.0               0.0              0.0   
...               ...          ...               ...              ...   
45206             0.0          0.0               0.0              1.0   
45207             0.0          0.0               1.0              0.0   
45208             0.0          0.0               0.0              1.0   
45209             0.0          0.0               0.0              1.0   
45210             0.0          0.0               0.0              1.0   

       marital_single  education_primary  education_secondary  \
0                 0.0                0.0                  0.0   
1                 1.0                0.0                  1.0   
2                 0.0                0.0                  1.0   
3                 0.0                0.0                  0.0   
4                 1.0                0.0                  0.0   
...               ...                ...                  ...   
45206             0.0                0.0                  0.0   
45207             0.0                1.0                  0.0   
45208             0.0                0.0                  1.0   
45209             0.0                0.0                  1.0   
45210             0.0                0.0                  1.0   

       education_tertiary  education_unknown  
0                     1.0                0.0  
1                     0.0                0.0  
2                     0.0                0.0  
3                     0.0                1.0  
4                     0.0                1.0  
...                   ...                ...  
45206                 1.0                0.0  
45207                 0.0                0.0  
45208                 0.0                0.0  
45209

In [22]:
y = le.fit_transform(y)

# Splitting the dataset into the Training set and Test set

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

# Feature Scaling

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Training the Logistic Classification model on the Training set
score - 0.8900807254229791

In [25]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)


LogisticRegression(random_state=0)

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

[[7854  139]
 [ 855  195]]
0.8900807254229791
Accuracy: 88.88 %
Standard Deviation: 0.36 %


# Training the K-NN Classification model on the Training set
Score - 0.8768107928784695

In [27]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [28]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

[[7675  318]
 [ 796  254]]
0.8768107928784695
Accuracy: 88.24 %
Standard Deviation: 0.33 %


# Training the SVC Classification model on the Training set
Score - 0.8838880902355413

In [29]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [30]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

[[7993    0]
 [1050    0]]
0.8838880902355413
Accuracy: 88.28 %
Standard Deviation: 0.01 %


# Training the Random Forest classification model on the Training set

In [31]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [32]:
y_pred2 = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred2)
print(cm)
print(accuracy_score(y_test, y_pred2))
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

[[7746  247]
 [ 791  259]]
0.8852150834899922
Accuracy: 88.38 %
Standard Deviation: 0.29 %


# Training the XGBoost classification model on the Training set

In [33]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [34]:
y_pred3 = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred3)
print(cm)
print(accuracy_score(y_test, y_pred3))
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

[[7760  233]
 [ 761  289]]
0.8900807254229791
Accuracy: 88.92 %
Standard Deviation: 0.36 %
